name: checkov

on:
  push:
    branches:
      - master
  pull_request:
      branches: [ master]

jobs: 
  checkov:
    name: Checkov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Checkov
        uses: bridgecrewio/checkov-action@master
        continue-on-error: true 
        with:
          directory: .
          framework: all
          quiet: true
          soft_fail: true
          download_external_modules: true
          log_level: INFO # One of: INFO, WARNING, DEBUG
          output_format: sarif
      - name: Upload Sarif file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif