name: trivy

on:
  push:
    branches:
      - master

jobs:
  trivy:
    name: trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t trivy-image:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'trivy-image:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

  anchore:
    name: Anchore
    runs-on: ubuntu-latest
    needs: trivy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Docker Build
        run: |
          docker build -t anchore-image:${{ github.sha }} . 
      - name: Anchore
        uses: anchore/scan-action@v3
        continue-on-error: true 
        id: scan
        with:
          image: anchore-image:${{ github.sha }}
          fail-build: false
          severity-cutoff: high # one of: negligible, low, medium, high, critical
          acs-report-enable: true
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}